version: '3.9'

services:
  storefrontdb:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
 
    volumes:
    - 'postgres:/var/lib/postgresql/data'

  teststorefrontdb:
    image: postgres
    ports:
      - '${POSTGRES_TEST_PORT}:${POSTGRES_TEST_PORT}'
    env_file:
      - .env
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_TEST_DB}

volumes:
  postgres: