version: '3.9'

services:
  postgres:
    container_name: storefrontdb
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB},${POSTGRES_TEST_DB}
 
    volumes:
      -'postgres:/var/lib/postgresql/data'

volumes:
  postgres: